### ISSUE TITLE
session.lua中与redis连接的问题

### ISSUE THREAD

**Issue by liujl** [mashijie/finity#1]
hi 你好，看到你的session.lua文件中每建立一个websocket请求都会去订阅redis的channel,这样是不是会导致与redis的连接数与websocket的连接数至少是1:1的关系，假如有8000个websocket同时连接，那意味着你的nginx与redis至少有8000个tcp连接? 谢谢

**Comment by mashijie** [comment]
是的，首先承认这种方案不是很好。
但是要做多worker或者多nginx之间的通信，没有什么比较好的方案。
我们目前更倾向于单ngx配单worker，分服的方式，服务器之间的通信再用redis中转





在 2017-01-22 15:14:09，"liujl" <notifications@github.com> 写道：


hi 你好，看到你的session.lua文件中每建立一个websocket请求都会去订阅redis的channel,这样是不是会导致与redis的连接数与websocket的连接数至少是1:1的关系，假如有8000个websocket同时连接，那意味着你的nginx与redis至少有8000个tcp连接? 谢谢
